Console.WriteLine("Salam gay boys!");
int a = Convert.ToInt32(Console.ReadLine());
int b = Convert.ToInt32(Console.ReadLine());
double e = Convert.ToDouble(Console.ReadLine()); 
double f = Convert.ToDouble(Console.ReadLine()); 
string? c = Convert.ToString(Console.ReadLine()); 
string? d = Convert.ToString(Console.ReadLine());
var sum =a + b;
var summ= a * b;
var summm = a % b;
var summmm = a - b;
var sum1= e + f;
var sum11 = e - f; 
var sum111 = e * f;
var sum1111 = e % f; 
var sum2 = c + d;
Console.WriteLine(sum); 
Console.WriteLine(summ);
Console.WriteLine(summm);
Console.WriteLine(summmm);
Console.WriteLine(sum1);
Console.WriteLine(sum11);
Console.WriteLine(sum111);
Console.WriteLine(sum1111);
Console.WriteLine(sum2);